//
// Created by Boris on 09-Oct-20.
//

#ifndef IFJ20_COMPILER_TOKEN_TYPES_H
#define IFJ20_COMPILER_TOKEN_TYPES_H

#define TOKEN_NONE -2
#define TOKEN_ERR -1
#define TOKEN_EOF 0
#define TOKEN_AB 2
#define TOKEN_10 3

#define TOKEN_KEYWORD_ELSE 4
#define TOKEN_KEYWORD_FLOAT64 5
#define TOKEN_KEYWORD_FOR 6
#define TOKEN_KEYWORD_FUNC 7
#define TOKEN_KEYWORD_IF 8
#define TOKEN_KEYWORD_INT 9
#define TOKEN_KEYWORD_PACKAGE 10
#define TOKEN_KEYWORD_RETURN 11
#define TOKEN_KEYWORD_STRING 12

#endif //IFJ20_COMPILER_TOKEN_TYPES_H
